### ISSUE TITLE
Construction site removal broken, completely locking up rooms on IVM private servers.

### ISSUE THREAD

**Issue by ags131** [screeps/engine#93]
Error and stacktrace below, this is on ScreepsPlus with the latest of the isolated-vm branch.
I've also adjusted package.json to point at `src` rather than `dist` to allow for easier testing of various patches, however, I also get this error on a completely stock engine too.
```
Error processing room E14S15: Error: Cannot find module './construction-sites/remove'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.exports.execute (/screeps/node_modules/@screeps/engine/src/processor/intents/movement.js:177:13)
    at module.exports (/screeps/node_modules/@screeps/engine/src/processor/intents/creeps/tick.js:48:18)
    at _.forEach (/screeps/node_modules/@screeps/engine/src/processor.js:243:59)
    at /screeps/node_modules/lodash/index.js:3073:15
    at baseForOwn (/screeps/node_modules/lodash/index.js:2046:14)
    at /screeps/node_modules/lodash/index.js:3043:18
    at Function.<anonymous> (/screeps/node_modules/lodash/index.js:3346:13)
    at q.when.then (/screeps/node_modules/@screeps/engine/src/processor.js:230:11)
    at _fulfilled (/screeps/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/screeps/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/screeps/node_modules/q/q.js:816:13)
    at /screeps/node_modules/q/q.js:570:49
    at runSingle (/screeps/node_modules/q/q.js:137:13)
    at flush (/screeps/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)```

**Comment by Creosteanu** [comment]
@ags131 is this still relevant?

**Comment by ags131** [comment]
It is still an issue, [this line](https://github.com/screeps/engine/blob/master/src/processor/intents/movement.js#L177) is the culprit since `construction-sites/remove` no longer exists as of https://github.com/screeps/engine/commit/ce37264df2975b3a2f8243e6c77f644393833937
